name: autoRbinomReport

# Controls when the workflow will run
on:
  schedule:
    - cron: "0 8 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  generate:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@master
      - uses: r-lib/actions/setup-r@master

      # Set up R
      - name: Install packages
        run: |
         R -e "install.packges('ggplot2')"
         R -e "install.packges('knitr')"

      # Runs the script
      - name: Generate numbers update report
        run: Rscript generate_random.R
      
      # Commit to repo
      - name: Commit files
        run: |
         git config --local user.name actions-user
         git config --local user.email "actions@github.com"
         git add data/*
         git commit -am "GH ACTION $(date)"
         git push origin master
        env:
         REPO_KEY: ${{secrets.GITHUB_TOKEN}}
         username: github-actions
